apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service
  labels:
    app: market-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-service
  template:
    metadata:
      labels:
        app: market-service
    spec:
      containers:
      - name: market-service
        image: akashdocker29/market-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 9003
---
apiVersion: v1
kind: Service
metadata:
  name: market-service
  labels:
    app: market-service
spec:
  ports:
  - port: 9003
    protocol: TCP
  selector:
    app: market-service
  type: ClusterIP
