apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  labels:
    app: integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
      - name: integration-service
        image: akashdocker29/integration-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: integration-service
  labels:
    app: integration-service
spec:
  ports:
  - port: 9002
    protocol: TCP
  selector:
    app: integration-service
  type: ClusterIP
